### ISSUE TITLE
add log

### ISSUE THREAD

**Issue by ababythwumps** [Addanine/scicalc#20]

**Comment by ababythwumps** [comment]
I added sin, cosin, and tan

**Comment by ababythwumps** [comment]
don't really wanna deal with log bc of natural log vs the other logs

**Comment by ababythwumps** [comment]
I added an empty button for log and an empty function for it

**Comment by Addanine** [comment]
by log i think i meant a log of the recent equations that the user has entered but that works too

**Comment by ababythwumps** [comment]
Owen meant this kind of log

**Comment by ababythwumps** [comment]
We have a different issue saying log doesn't work and we do have a log now so I'm closing this issue
