### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by Addanine** [Addanine/scicalc#6]
add some damn comments to this code

**Comment by Addanine** [comment]
ill do it i just wanted to remind myself

**Comment by ababythwumps** [comment]
I can do it

**Comment by ababythwumps** [comment]
it's fine

**Comment by ababythwumps** [comment]
GOD DAMN WE NEED COMMENTS

**Comment by Addanine** [comment]
saw my newest commit and said we needed comments

**Comment by Addanine** [comment]
ill add comments to future commits

**Comment by Addanine** [comment]
added commits to the JS and i dont think the HTML or CSS needs it, in the future everyone please add comments @ababythwumps @Owen654.
