### ISSUE TITLE
move button layout to python side

### ISSUE THREAD

**Issue by ae1313** [Addanine/scicalc#8]
It's really miserable to work with right now.

**Comment by Addanine** [comment]
frontend js is so much easier than frontend python tho

**Comment by ababythwumps** [comment]
true but if python is faster...

**Comment by ae1313** [comment]
It’s not about speed. Just make it more logical. Maybe put each row into a different div. just something

**Comment by ababythwumps** [comment]
🫤but then I agree with Harry...

**Comment by ae1313** [comment]
Also no the python wouldn’t be fronted. I was talking about using the templates more

**Comment by ae1313** [comment]
I’ll just explain in person it’ll make more sense
